# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9363c0231ecfe09d4210526fe9d226f2eafa51f95b4569da15c081639ac29ab7652edaf96e3e9641194efcff946abaece97c35be11ea40fa2bcea81fb33b613

test:
  secret_key_base: 8158d753c622fe6e2fe2b60d6e69e3a1c3d07e6369dd55f15bf45e064552bc3ee2268c1fccef605d3ed9c957b72aa1f93f27aa009f627b584f5f1d3adcfa2c4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
